name: Deploy Azure Function (Python)

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'host.json'
      - '.funcignore'
      - 'requirements.txt'
      - 'pyproject.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true
      - name: Build package
        run: |
          pip install -r requirements.txt
          func pack --build-native-deps --python
          ls -la
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_JSON }}
          # OR use publish profile:
          # publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
      - name: Deploy
        run: |
          func azure functionapp publish ${{ secrets.AZURE_FUNCTIONAPP_NAME }} --python
